=== TERINO-73/1-DAW/Lenguaje De Marcas/LM.Boletín_8/3/discoteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="discoteca" type="tdiscoteca"/>
 
 <xs:complexType name="tdiscoteca">
      <xs:sequence>
        <xs:element name="cancion" type="tcancion" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence> 
    </xs:complexType>
    
        <xs:complexType name="tcancion" >
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="autor" type="tautor"/>
        <xs:element name="interprete">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="solista" type="ttsolista"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="estilo" type="xs:string" minOccurs="0"/>
        <xs:element name="promocion" type="tpromocion"/>
      </xs:sequence> 
    </xs:complexType>
    
    <xs:complexType name="tautor" >
      <xs:sequence>
        <xs:element name="letra" type="xs:string" maxOccurs="unbounded"/>
        <xs:element name="musica" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence> 
    </xs:complexType>

    
    <xs:simpleType name="ttsolista">
    <xs:restriction base="xs:string">
      <xs:enumeration value="si"/>
      <xs:enumeration value="no"/>
    </xs:restriction>  
  </xs:simpleType>
  
    <xs:complexType name="tpromocion" >
      <xs:choice>
          <xs:element name="radio" type="tradio"/>
          <xs:element name="festival" type="tfestival"/>
      </xs:choice> 
    </xs:complexType>
    
        <xs:complexType name="tfestival" >
      <xs:sequence>
        <xs:element name="ciudad" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence> 
      </xs:complexType>
    
    
        <xs:complexType name="tradio" >
      <xs:sequence>
        <xs:element name="emisora" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence> 
    </xs:complexType>
</xs:schema>

=== TERINO-73/1-DAW/Lenguaje De Marcas/LM.Boletín_8/3/discoteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<discoteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="discoteca.xsd">
 <cancion>
 <titulo>Las nanas de la cebolla</titulo>
 <autor>
 <letra>Miguel Hernández</letra>
 <musica>Joan Manuel Serrat</musica>
 </autor>
 <interprete solista="si">Joan Manuel Serrat</interprete>
 <estilo>cantautor</estilo>
 <promocion>
 <festival>
 <ciudad>Tarragona</ciudad>
 </festival>
 </promocion>
 </cancion>

 <cancion>
 <titulo>Comandante Marcos</titulo>
 <autor>
 <letra>Joaquín Sabina</letra>
 <letra>Comandante Marcos</letra>
 <musica>Desconocido</musica>
 </autor>
 <interprete>Joaquín Sabina</interprete>
 <estilo>canción canallesca</estilo>
 <promocion>
 <radio>
 <emisora>radio OLE</emisora>
 <emisora>M80</emisora>
 </radio>
 </promocion>
 </cancion>

 <cancion>
 <titulo>Paseo con la negra flor</titulo>
 <autor>
 <letra>Santiago Serón</letra>
 <musica>Santiago Serón</musica>
 <musica>Alberto Múgica</musica>
 </autor>
 <interprete solista="no">Radio Futura</interprete>
 <promocion>
 <radio>
 <emisora>Radio 3</emisora>
 </radio>
 </promocion>
 </cancion>

</discoteca>
