=== TERINO-73/1-DAW/Lenguaje De Marcas/.Examenes/examen xsd/datos.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="fichas" type="tFichas"/>
    <xs:complexType name="tFichas">
      <xs:sequence>
          <xs:element name="ficha" type="tFicha" maxOccurs="unbounded"/>
      </xs:sequence>

      </xs:complexType>
        <xs:complexType name="tFicha">
          <xs:sequence>
            <xs:choice>
              <xs:element name="iniciales" type="tIniciales"/>
              <xs:element name="nombre" type="xs:string"/>
            </xs:choice>
                  
            <xs:choice>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="iniciales" type="tIniciales"/>
            </xs:choice>
            <xs:element name="edad" type="xs:integer"/>
          </xs:sequence>
          <xs:attribute name="dni" type="tDni"/>
      </xs:complexType>

      <xs:simpleType name="tIniciales">
        <xs:restriction base="xs:string">
          <xs:pattern value="[A-Z]{3}"/>
          <xs:pattern value="[a-z]{3}"/>
          <xs:pattern value="[A-Z]{2}"/>
          <xs:pattern value="[a-z]{2}"/>
       </xs:restriction>
      </xs:simpleType>
      
      <xs:simpleType name="tDni">
            <xs:restriction base="xs:string">
                <xs:pattern value="\d{8}[A-Z]{1}"/>
                <xs:pattern value="[A-Z]{1}\d{8}"/>
            </xs:restriction>
      </xs:simpleType>

</xs:schema>

=== TERINO-73/1-DAW/Lenguaje De Marcas/.Examenes/examen xsd/datos.xml
<fichas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="datos.xsd">
<ficha dni="22222222D">
<nombre>Antonio Machado Ruiz</nombre>
<iniciales>AMR</iniciales>
<edad>22</edad>
</ficha>
<ficha dni="33333333S">
<iniciales>MM</iniciales>
<nombre>Mario Moreno</nombre>
<edad>23</edad>
</ficha>
<ficha dni="44444444F">
<nombre>Ada Lovelace</nombre>
<iniciales>ALO</iniciales>
<edad>24</edad>
</ficha>
<ficha dni="55555555A">
<nombre>pablo ruiz picasso</nombre>
<iniciales>prp</iniciales>
<edad>24</edad>
</ficha>
</fichas>
