=== TERINO-73/1-DAW/Lenguaje De Marcas/LM.Boletin_5/LM.boletin_5_ej2/LM_B5_ej2_dtd.dtd
<!ELEMENT pedidos (pedido*)>
<!ELEMENT pedido (producto,datos_entrega,datos_comprador)>
<!ELEMENT producto (nombre,codigo,cantidad,precio,precio_total)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT precio_total (#PCDATA)>
<!ELEMENT datos_entrega (direccion,fecha)>
<!ELEMENT direccion (ciudad,codigo_postal,calle)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT datos_comprador (nombre_completo,receptor)>
<!ELEMENT nombre_completo (#PCDATA)>
<!ELEMENT receptor (#PCDATA)>

=== TERINO-73/1-DAW/Lenguaje De Marcas/LM.Boletin_5/LM.boletin_5_ej2/LM_B5_ej2_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE pedidos SYSTEM "LM_B5_ej2_dtd.dtd">
  <pedidos>
    <pedido>
      <producto>
        <nombre>cortadora de cesped</nombre>
        <codigo>COR277</codigo>
        <cantidad>1</cantidad>
        <precio>126,27</precio>
        <precio_total>126,27</precio_total>
      </producto>
      <datos_entrega>
        <direccion>
          <ciudad>Malaga</ciudad>
          <codigo_postal>29011</codigo_postal>
          <calle>Plaza de la Merced,12</calle>
        </direccion>
        <fecha>10-01-23</fecha>
      </datos_entrega>
      <datos_comprador>
        <nombre_completo>Juan Perez</nombre_completo>
        <receptor>Maria Garcia</receptor>
      </datos_comprador>
    </pedido>
    
    <pedido>
      <producto>
        <nombre>Podadora</nombre>
        <codigo>POD221</codigo>
        <cantidad>3</cantidad>
        <precio>12,95</precio>
        <precio_total>38,85</precio_total>
      </producto>
      <datos_entrega>
        <direccion>
          <ciudad>Jaen</ciudad>
          <codigo_postal>23006</codigo_postal>
          <calle>Calle Libertadores,56</calle>
        </direccion>
        <fecha>10-01-23</fecha>
      </datos_entrega>
      <datos_comprador>
        <nombre_completo>Juan Perez</nombre_completo>
        <receptor>Juan Perez</receptor>
      </datos_comprador>
    </pedido>
</pedidos>
