=== TERINO-73/1-DAW/Lenguaje De Marcas/LM.Boletín_8/1/LM_B8_ej1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="juzgados" type="tjuzgados"/>

    <xs:complexType name="tjuzgados" >
      <xs:sequence>
        <xs:element name="sala" type="tsala"/>
      </xs:sequence> 
    </xs:complexType>

    <xs:complexType name="tsala" >
      <xs:sequence>
        <xs:element name="caso" type="tcaso"/>
      </xs:sequence> 
        <xs:attribute name="numero" type="ttsala"/>
    </xs:complexType>
    
    <xs:simpleType name="ttsala">
      <xs:restriction base="xs:integer">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="7"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="tcaso" >
      <xs:sequence>
        <xs:element name="juez" type="tjuez"/>
        <xs:element name="acusadora" type="tacusadora"/>
        <xs:element name="acusada" type="tacusada"/>
      </xs:sequence> 
        <xs:attribute name="numero" type="xs:ID"/>
    </xs:complexType>
    
   
    
    <xs:complexType name="tjuez">
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="dni" type="ttdni"/>
        <xs:element name="numColg" type="ttnumColg"/>
      </xs:sequence> 
    </xs:complexType>
    
  <xs:simpleType name="ttdni">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{8}[A-Z]{1}"/>
      <xs:pattern value="[A-Z]{1}\d{8}"/>
    </xs:restriction>
  </xs:simpleType>
    
    <xs:simpleType name="ttnumColg">
      <xs:restriction base="xs:ID">
      <xs:pattern value="[A-Z]{2}-\d{4}-[A-Z]{1}"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="tacusadora">
      <xs:sequence>
        <xs:element name="persona" type="tpersona" maxOccurs="unbounded"/>
        <xs:element name="fiscal" type="tfiscal"/>
        <xs:element name="abogado" type="tabogado"/>
      </xs:sequence> 
    </xs:complexType>
    
      <xs:complexType name="tpersona" >
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="dni" type="ttdni"/>
        <xs:element name="fechaNac" type="xs:date"/>
        <xs:element name="antecedentes" type="ttantecedentes" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="sexo" type="tsexo" default="Masculino"/>
      </xs:sequence> 
    </xs:complexType>
    
    <xs:simpleType name="tsexo">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Masculino"/>
      <xs:enumeration value="Femenino"/>
    </xs:restriction>  
  </xs:simpleType>
    
    <xs:complexType name="ttantecedentes" >
        <xs:attribute name="delito" type="ttdelito"/>
        <xs:attribute name="meses" type="xs:integer"/>
        <xs:attribute name="años" type="xs:integer"/>
    </xs:complexType>
    
    <xs:simpleType name="ttdelito">
      <xs:restriction base="xs:string">
        <xs:enumeration value="Robo"/>
        <xs:enumeration value="Asesinato"/>
        <xs:enumeration value="Actos Violentos"/>
      </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="tfiscal">
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="dni" type="ttdni"/>
        <xs:element name="numColg" type="ttnumColg"/>
      </xs:sequence> 
    </xs:complexType>
    
    <xs:complexType name="tabogado" >
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="dni" type="ttdni"/>
        <xs:element name="numColg" type="ttnumColg"/>
      </xs:sequence> 
    </xs:complexType>
    
        <xs:complexType name="tacusada">
      <xs:sequence>
        <xs:element name="persona" type="tpersona" maxOccurs="unbounded"/>
        <xs:element name="abogado" type="tabogado"/>
      </xs:sequence> 
    </xs:complexType>
    
    
    
    


</xs:schema>

=== TERINO-73/1-DAW/Lenguaje De Marcas/LM.Boletín_8/1/LM_B8_ej1.xml
<?xml version="1.0" encoding="UTF-8"?>
<juzgados xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="LM_B8_ej1.xsd">
  <sala numero="1">
    <caso numero="A1">
      <juez>
        <nombre>Juan</nombre>
        <apellidos>Gómez García</apellidos>
        <dni>28441844X</dni>
        <numColg>SE-2222-D</numColg>
      </juez>
      <acusadora>
        <persona>
          <nombre>Luis</nombre>
          <apellidos>Perez</apellidos>
          <dni>52741963D</dni>
          <fechaNac>1980-12-30</fechaNac>
          <sexo>Masculino</sexo>
        </persona>
        <persona>
          <nombre>Luis</nombre>
          <apellidos>Gomez</apellidos>
          <dni>52855963X</dni>
          <fechaNac>1912-12-30</fechaNac>
          <sexo>Masculino</sexo>
        </persona>
        <fiscal>
          <nombre>Antonio</nombre>
          <apellidos>Garcia Serna</apellidos>
          <dni>27451852X</dni>
          <numColg>SE-2005-D</numColg>
        </fiscal>
        <abogado>
          <nombre>Juan</nombre>
          <apellidos>Perez Serrano</apellidos>
          <dni>28000852X</dni>
          <numColg>MA-7645-D</numColg>
        </abogado>
      </acusadora>
      <acusada>
        <persona>
          <nombre>Luis</nombre>
          <apellidos>Jimenz Vázquez</apellidos>
          <dni>52853963X</dni>
          <fechaNac>1970-02-28</fechaNac>
          <antecedentes delito="Robo" meses="3"></antecedentes>
          <antecedentes delito="Asesinato" años="12" meses="2"></antecedentes>
          <sexo>Masculino</sexo>
        </persona>
        <persona>
          <nombre>José</nombre>
          <apellidos>Pelaez Rodriguez</apellidos>
          <dni>44641852X</dni>
          <fechaNac>1999-12-05</fechaNac>
          <sexo>Masculino</sexo>
        </persona>
        <abogado>
          <nombre>Juan Luis</nombre>
          <apellidos>Guitierrez Pérez</apellidos>
          <dni>95541852X</dni>
          <numColg>MU-2345-X</numColg>
        </abogado>
      </acusada>
    </caso>
  </sala>
</juzgados>
