=== TERINO-73/1-DAW/Lenguaje De Marcas/LM.Boletin_5/LM.boletin_5_ej4/LM_B5_ej4_dtd.dtd
<!ELEMENT juzgados (sala)>
<!ATTLIST sala numero CDATA #REQUIRED>
<!ELEMENT sala (caso)>
<!ATTLIST caso numero CDATA #REQUIRED>
<!ELEMENT caso (juez,acusadora,acusada)>
<!ELEMENT juez (nombre,apellidos,dni,numColg)>
<!ELEMENT acusadora (persona*,fiscal,abogado)>
<!ELEMENT persona (nombre,apellidos,dni,fechaNac,antecedentes*)>
<!ELEMENT fiscal (nombre,apellidos,dni,numColg)>
<!ELEMENT abogado (nombre,apellidos,dni,numColg)>
<!ELEMENT acusada (persona*,abogado*)>
<!ELEMENT antecedentes (#PCDATA)>
<!ATTLIST antecedentes delito (Asesinato|Robo|Actos_violentos) #IMPLIED>
<!ATTLIST antecedentes aÃ±os CDATA #IMPLIED>
<!ATTLIST antecedentes meses CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT numColg (#PCDATA)>
<!ELEMENT fechaNac (#PCDATA)>

=== TERINO-73/1-DAW/Lenguaje De Marcas/LM.Boletin_5/LM.boletin_5_ej4/LM_B5_ej4_xml.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE juzgados SYSTEM "LM_B5_ej4_dtd.dtd">
<juzgados>
 <sala numero="1">
 <caso numero="A1">
 <juez>
 <nombre>Juan</nombre>
 <apellidos>Gómez García</apellidos>
 <dni>28441854X</dni>
 <numColg>SE-2222-D</numColg>
 </juez>
 <acusadora>
   <persona>
     <nombre>Luis</nombre>
     <apellidos>Perez</apellidos>
     <dni>52741963D</dni>
     <fechaNac>1980-12-30</fechaNac>
   </persona>
   <persona>
     <nombre>Luis</nombre>
     <apellidos>Gomez</apellidos>
     <dni>52855963X</dni>
     <fechaNac>1912-12-30</fechaNac>
   </persona>
    <fiscal>
      <nombre>Antonio</nombre>
      <apellidos>Garcia Serna</apellidos>
      <dni>27451852X</dni>
      <numColg>SE-2005-D</numColg>
    </fiscal>
    <abogado>
       <nombre>Juan</nombre>
       <apellidos>Perez Serrano</apellidos>
       <dni>28000852X</dni>
       <numColg>MA-7645-D</numColg>
    </abogado>
 </acusadora>
 <acusada>
 <persona>
 <nombre>Luis</nombre>
 <apellidos>Jimenz Vázquez</apellidos>
 <dni>52852963X</dni>
 <fechaNac>1970-02-28</fechaNac>
 <antecedentes delito="Robo" meses="3"></antecedentes>
 <antecedentes delito="Asesinato" años="12" meses="2"></antecedentes>
 </persona>
 <persona>
 <nombre>José</nombre>
 <apellidos>Pelaez Rodriguez</apellidos>
 <dni>44641852X</dni>
 <fechaNac>1999-12-05</fechaNac>
 </persona>
 <abogado>
 <nombre>Juan Luis</nombre>
 <apellidos>Guitierrez Pérez</apellidos>
 <dni>95541852X</dni>
 <numColg>MU-2345-X</numColg>
 </abogado>
 </acusada>
 </caso>
 </sala>
</juzgados>
